server:
  port: 8887

camunda.bpm:
    admin-user:
      id: demo
      password: demo
    filter.create: All

spring.datasource:
  url: jdbc:h2:./.camunda-h2-default/process-engine;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
  username: camunda
  password: camunda
  driver-class-name: org.h2.Driver